### ISSUE TITLE
Name Stem not accetped

### ISSUE THREAD

**Issue by AlasdairGray** [HeriotWattMEng2015/ShEx-validator#21]
ShEx parser does not accept the pattern  ```:chemb dct:accrualPeriodicity freq:~?.```

**Comment by tar672** [comment]
There seems to be a number of issues currently with both name and value stems.

As far as I can tell the parser does not like the use of value stems with cardinality modifiers.

Also currently RDF.js throws an error when either stem is used. This is a trivial fix though.

Should get both fixed soon.

**Comment by tar672** [comment]
Name stems fixed by 660186d5dcb967c0c2403e91a91df79ec2897aed

Value stems throw parse error. @jacobbaungard could you have a look?

**Comment by tar672** [comment]
Added failing test for data stem cfdf60bbb9d33

**Comment by jacobbaungard** [comment]
Support for parsing value stems has been added in the value_stems branch. It does not look like RDF.js currently supports this in the validation phase.

**Comment by jacobbaungard** [comment]
Value stems fixed, and pull request made.
