### ISSUE TITLE
Parsers: Investigate Eric's validation code and figure out how to pull in more parsed data 

### ISSUE THREAD

**Issue by tar672** [HeriotWattMEng2015/ShEx-validator#5]
_From @andrewthecoder on February 3, 2015 15:6_

Modify/ write the JS code to take the parsed Schema and Data and actually perform validation, with useful error messages which are simple enough to help the user. Probably building on top of Eric's work: 
https://github.com/ericprud/ShExDemo/blob/master/demobits/ShExDemo.js

_Copied from original issue: HeriotWattMEng2015/ShExDemo#8_

**Comment by tar672** [comment]
@Doix and I are working on it

**Comment by andrewthecoder** [comment]
FYI, Jesse's old RDF.js is here: https://github.com/jessevdam/shextest/blob/master/js/RDF.js

**Comment by tar672** [comment]
This is being handled by #4
